### ISSUE TITLE
'SymoCMD' was not registered by any plugin

### ISSUE THREAD

**Issue by felipetng** [kgws/homebridge-temperature-cmd#5]
I having this issue: 

 Error: The requested accessory 'SymoCMD' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

What I need to do to fix this?

**Comment by geinzmrk** [comment]
i get the same error +1

**Comment by clarkesatbay** [comment]
Found a very simple syntax error in index.js 

Line was:
const DEF_MIN_LUX = 0,
      DEF_MAX_LUX = 10000,

Line should be:

const DEF_MIN_LUX = 0,
      DEF_MAX_LUX = 10000;

Works now.
